const COMMANDS_DATA = {
    chutes: [
        { name: 'Chute / Voleio / Cabeceio', buttons: ['b'], icon: 'shoot', desc: 'Finalização básica a gol. Funciona parado, de primeira (voleio) ou de cabeça, dependendo da posição da bola.' },
        { name: 'Chute Colocado (Finesse)', buttons: ['rb', 'b'], icon: 'finesse', desc: 'Chute com mais curva e precisão, ideal para buscar o canto do gol à distância.' },
        { name: 'Chute Forte (Power Shot)', buttons: ['lb', 'rb', 'b'], icon: 'power', desc: 'Chute carregado com mais força, útil de fora da área, mas com menor precisão.' },
        { name: 'Cavadinha (Chip Shot)', buttons: ['lb', 'b'], icon: 'chip', desc: 'Levanta a bola por cima do goleiro adiantado. Boa opção em bolas na saída do goleiro.' },
        { name: 'Chute Rasteiro Forte', buttons: ['b', 'b'], icon: 'power', desc: 'Chute forte mantendo a bola rente ao chão, dificultando a defesa do goleiro.' },
        { name: 'Chute Colocado Rasteiro', buttons: ['rb', 'b', 'b'], icon: 'finesse', desc: 'Combina curva do chute colocado com trajetória mais baixa e rasteira.' },
        { name: 'Chute Forte Rasteiro', buttons: ['lb', 'rb', 'b', 'b'], icon: 'power', desc: 'Versão rasteira do chute forte, unindo potência com trajetória baixa.' },
        { name: 'Chute Categorizado (Flair)', buttons: ['lt', 'b'], icon: 'bicycle', desc: 'Finalização estilosa, geralmente de calcanhar ou lateral, usada para surpreender o goleiro.' },
        { name: 'Bicicleta / Finalização Especial', buttons: ['rt', 'rs'], icon: 'bicycle', desc: 'Chute acrobático em bolas altas, ótimo para cruzamentos e rebotes no ar.' },
        { name: 'Cancelar Chute (Fake Shot)', buttons: ['b', 'a'], icon: 'fake', desc: 'Inicia o gesto de chute e cancela na sequência, enganando a marcação adversária.' },
        { name: 'Fake Shot para Chute', buttons: ['x', 'b', 'a'], icon: 'fake', desc: 'Finta de chute que engana o goleiro e finaliza logo em seguida na direção oposta.' },
        { name: 'Pênalti - Chute Colocado', buttons: ['rb', 'b'], icon: 'penalty', desc: 'Na cobrança de pênalti, direciona a bola com mais precisão para o canto escolhido.' },
        { name: 'Pênalti - Cavadinha', buttons: ['lb', 'b'], icon: 'penalty', desc: 'Cobrança de pênalti por cima, arriscada se o goleiro não sair adiantado.' },
        { name: 'Cobrança de Pênalti', buttons: ['b'], icon: 'penalty', desc: 'Chute padrão na marca do pênalti, com potência controlada pela barra de força.' }
    ],
    passes: [
        { name: 'Passe Rasteiro / Cabeceio', buttons: ['a'], icon: 'passShort', desc: 'Passe curto e direto ao companheiro mais próximo na direção do analógico.' },
        { name: 'Cruzamento / Lançamento', buttons: ['x'], icon: 'cross', desc: 'Cruza a bola na área ou lança para um jogador mais distante.' },
        { name: 'Passe em Profundidade', buttons: ['y'], icon: 'throughBall', desc: 'Passe entre os defensores para o companheiro correr até a bola.' },
        { name: 'Passe Rasteiro Forte', buttons: ['rb', 'a'], icon: 'passShort', desc: 'Passe rasteiro com mais velocidade, ideal para romper linhas de marcação.' },
        { name: 'Passe em Profundidade Alto', buttons: ['lb', 'y'], icon: 'passLong', desc: 'Lançamento em profundidade por cima da defesa, para o companheiro correr por trás.' },
        { name: 'Passe em Profundidade Forte', buttons: ['lb', 'rb', 'y'], icon: 'throughBall', desc: 'Combina velocidade e profundidade, útil em contra-ataques rápidos.' },
        { name: 'Cruzamento Forte', buttons: ['lb', 'rb', 'x'], icon: 'cross', desc: 'Cruzamento mais rápido e rasteiro, difícil de cortar pela defesa.' },
        { name: 'Cruzamento Alto', buttons: ['lb', 'x'], icon: 'cross', desc: 'Cruzamento alto e arqueado, bom para cabeceio na área.' },
        { name: 'Passe Duplo Toque', buttons: ['a', 'a'], icon: 'passShort', desc: 'Toque duplo no botão de passe para um passe mais rápido em sequência.' },
        { name: 'Lançamento Duplo Toque', buttons: ['y', 'y'], icon: 'passLong', desc: 'Toque duplo para lançamentos rápidos em profundidade.' },
        { name: 'Cruzamento Duplo Toque', buttons: ['x', 'x'], icon: 'cross', desc: 'Cruzamento mais ágil ao apertar o botão duas vezes seguidas.' },
        { name: 'Cruzamento Rasteiro Forte', buttons: ['lb', 'rb', 'x', 'x'], icon: 'cross', desc: 'Cruzamento forte e rasteiro na área, difícil de antecipar pelo goleiro.' },
        { name: 'Passe Categorizado (Flair)', buttons: ['lt', 'a'], icon: 'passShort', desc: 'Passe estilizado, geralmente de calcanhar ou externo do pé.' },
        { name: 'Lançamento Categorizado', buttons: ['lt', 'y'], icon: 'throughBall', desc: 'Passe em profundidade com efeito extra e trajetória mais criativa.' },
        { name: 'Cruzamento Categorizado', buttons: ['lt', 'x'], icon: 'cross', desc: 'Cruzamento com toque de estilo, útil para surpreender a defesa adversária.' },
        { name: 'Passe de Precisão', buttons: ['rb', 'y'], icon: 'throughBall', desc: 'Passe em profundidade mais preciso, ideal para achar espaços apertados.' },
        { name: 'Passe com Efeito de Precisão', buttons: ['lt', 'rb', 'y'], icon: 'throughBall', desc: 'Adiciona curva ao passe de precisão para contornar defensores.' },
        { name: 'Cruzamento de Precisão', buttons: ['rb', 'x'], icon: 'cross', desc: 'Cruzamento mais controlado, direcionado com maior exatidão para a área.' },
        { name: 'Cancelar Passe (Fake Pass)', buttons: ['x', 'a'], icon: 'fake', desc: 'Inicia o gesto de passe e cancela, útil para confundir a marcação.' },
        { name: 'Passe e Movimento (Pass and Go)', buttons: ['lb', 'a'], icon: 'passShort', desc: 'Passa e o jogador já inicia uma corrida de apoio automaticamente.' },
        { name: 'Passe e Correr', buttons: ['a', 'rs'], icon: 'passShort', desc: 'Após o passe, direciona a corrida do jogador com o analógico direito.' },
        { name: 'Pedir Apoio (Call for Support)', buttons: ['rb'], icon: 'support', desc: 'Chama um companheiro para se posicionar como opção de passe.' },
        { name: 'Apoio Duplo', buttons: ['rb', 'rb'], icon: 'support', desc: 'Chama dois companheiros simultaneamente para dar apoio ao jogador com a bola.' },
        { name: 'Disfarçar Passe (Dummy)', buttons: ['ls', 'rb'], icon: 'dummy', desc: 'O jogador deixa a bola passar entre as pernas para um companheiro atrás.' },
        { name: 'Deixar a Bola Rolar', buttons: ['rb', 'ls'], icon: 'dummy', desc: 'O jogador ignora a bola recebida para outro companheiro continuar a jogada.' },
        { name: 'Elevar a Bola (Flick Up)', buttons: ['rs'], icon: 'ballRoll', desc: 'Levanta a bola do chão, útil para iniciar um voleio ou driblar de saída.' },
        { name: 'Corridas Direcionais', buttons: ['lb', 'rs'], icon: 'support', desc: 'Direciona a corrida de um companheiro para um espaço específico do campo.' },
        { name: 'Travar Jogador (Player Lock)', buttons: ['ls', 'rs'], icon: 'lock', desc: 'Fixa o controle em um jogador específico, ignorando trocas automáticas.' }
    ],
    dribles: [
        { name: 'Jogadas de Habilidade (Skill Moves)', buttons: ['rs'], icon: 'skillMove', desc: 'Movimente o analógico direito para executar dribles e fintas com o jogador.' },
        { name: 'Ball Roll', buttons: ['rs'], icon: 'ballRoll', desc: 'Gira a sola do pé sobre a bola para mudar de direção rapidamente.' },
        { name: 'Step Over', buttons: ['rs'], icon: 'skillMove', desc: 'Finta clássica passando a perna por cima da bola para enganar o marcador.' },
        { name: 'Heel to Heel Flick', buttons: ['rs'], icon: 'skillMove', desc: 'Toque de calcanhar para calcanhar, drible rápido em espaços curtos.' },
        { name: 'Toque Controlado (First Touch)', buttons: ['rt', 'rs'], icon: 'firstTouch', desc: 'Direciona o primeiro toque na bola ao recebê-la, controlando o espaço à frente.' },
        { name: 'Toque com Efeito (Knock-On)', buttons: ['rt', 'rs'], icon: 'firstTouch', desc: 'Empurra a bola à frente com o primeiro toque para ganhar espaço em corrida.' },
        { name: 'Toque Controlado Avançado', buttons: ['rb', 'rs'], icon: 'firstTouch', desc: 'Versão mais sutil do toque controlado, ideal em espaços apertados.' },
        { name: 'Toque de Esforço (Effort Touch)', buttons: ['rb', 'rs'], icon: 'firstTouch', desc: 'Toque mais intenso para acelerar a saída da bola em corridas longas.' },
        { name: 'Parar e Encarar o Gol', buttons: ['ls', 'lb'], icon: 'stop', desc: 'Interrompe o drible e reposiciona o jogador de frente para o gol adversário.' },
        { name: 'Drible Lateral (Strafe Dribble)', buttons: ['lb', 'ls'], icon: 'ballRoll', desc: 'Movimento lateral controlado, útil para escapar da marcação sem perder o ângulo.' },
        { name: 'Sprint Controlado', buttons: ['rb'], icon: 'sprint', desc: 'Corre mantendo controle mais próximo da bola, sacrificando um pouco de velocidade.' },
        { name: 'Parar a Bola (Stop Ball)', buttons: ['ls', 'rt'], icon: 'stop', desc: 'Trava a bola embaixo do pé, útil para mudar o ritmo da jogada de repente.' },
        { name: 'Finta de Chute p/ Abrir Esquerda', buttons: ['lb', 'x'], icon: 'fake', desc: 'Finge o chute para abrir espaço e seguir driblando pela esquerda.' },
        { name: 'Finta de Chute p/ Abrir Direita', buttons: ['lb', 'x'], icon: 'fake', desc: 'Finge o chute para abrir espaço e seguir driblando pela direita.' },
        { name: 'Finta de Calcanhar (Parado)', buttons: ['lt', 'rs'], icon: 'skillMove', desc: 'Drible de calcanhar executado com o jogador parado, surpreendendo o marcador.' },
        { name: 'Arco-íris de Estilo', buttons: ['lb', 'rs'], icon: 'skillMove', desc: 'Levanta a bola por cima da cabeça do adversário em um movimento de efeito.' },
        { name: 'Toque Disfarçado (Disguised First Touch)', buttons: ['lb', 'rb', 'ls'], icon: 'firstTouch', desc: 'Disfarça a direção do primeiro toque para confundir o defensor mais próximo.' },
        { name: 'Proteger a Bola', buttons: ['lt'], icon: 'shield', desc: 'Usa o corpo para blindar a bola do adversário, mantendo a posse.' },
        { name: 'Blindar / Impulsionar (Jockey)', buttons: ['lt'], icon: 'shield', desc: 'Protege a bola enquanto avança lentamente contra a marcação.' },
        { name: 'Entrar na Proteção (Push Back)', buttons: ['lt'], icon: 'shield', desc: 'Empurra o defensor para trás enquanto protege a posse de bola.' }
    ],
    defesa: [
        { name: 'Trocar Jogador', buttons: ['lb'], icon: 'switchPlayer', desc: 'Alterna automaticamente para o jogador mais próximo da bola ou da jogada.' },
        { name: 'Trocar Jogador (Manual)', buttons: ['rs'], icon: 'switchPlayer', desc: 'Escolhe manualmente qual jogador controlar usando a direção do analógico.' },
        { name: 'Troca por Ícone (Icon Switching)', buttons: ['r3'], icon: 'switchPlayer', desc: 'Ativa o modo de troca por ícones, mostrando setas para cada jogador na tela.' },
        { name: 'Desarme (Tackle)', buttons: ['b'], icon: 'tackle', desc: 'Tenta tomar a bola do adversário com um desarme simples ao seu lado.' },
        { name: 'Empurrar / Puxar ao Perseguir', buttons: ['b'], icon: 'tackle', desc: 'Disputa física de corpo enquanto persegue o jogador adversário com bola.' },
        { name: 'Desarme Forte (Hard Tackle)', buttons: ['rb', 'b'], icon: 'tackle', desc: 'Desarme mais agressivo, com maior chance de recuperar a bola mas de falta.' },
        { name: 'Falta Proposital (Professional Foul)', buttons: ['rb', 'a'], icon: 'foul', desc: 'Comete falta de forma intencional para interromper um contra-ataque perigoso.' },
        { name: 'Carrinho (Sliding Tackle)', buttons: ['x'], icon: 'slide', desc: 'Desarme deslizando pelo chão, arriscado mas eficaz para cortar a jogada.' },
        { name: 'Carrinho Forte', buttons: ['rb', 'x'], icon: 'slide', desc: 'Carrinho com mais impacto, aumenta o risco de cartão se mal cronometrado.' },
        { name: 'Afastamento (Clearance)', buttons: ['b'], icon: 'clearance', desc: 'Afasta a bola da área de perigo com um chute forte sem direção específica.' },
        { name: 'Afastamento Técnico', buttons: ['rb', 'b'], icon: 'clearance', desc: 'Afastamento mais controlado, direcionando melhor para onde a bola vai.' },
        { name: 'Disputa de Ombro (Shoulder Challenge)', buttons: ['b'], icon: 'jostle', desc: 'Disputa a bola no ar ou corpo a corpo usando o ombro para desequilibrar o rival.' },
        { name: 'Conter Adversário (Contain)', buttons: ['a'], icon: 'contain', desc: 'Mantém distância segura do atacante, pressionando sem se comprometer no desarme.' },
        { name: 'Desarme Físico (Advanced Defending)', buttons: ['a'], icon: 'contain', desc: 'No modo de defesa avançada, pressiona fisicamente o portador da bola.' },
        { name: 'Pedir Apoio Defensivo', buttons: ['rb'], icon: 'support', desc: 'Chama um companheiro para ajudar a fechar espaços na marcação.' },
        { name: 'Pressão Parcial da Equipe', buttons: ['rb', 'rb'], icon: 'press', desc: 'Ativa pressão de parte do time sobre o portador da bola adversário.' },
        { name: 'Jockey em Sprint', buttons: ['lt', 'rt'], icon: 'shield', desc: 'Acompanha o adversário em alta velocidade mantendo a posição defensiva.' },
        { name: 'Levantar Rápido (após carrinho)', buttons: ['x'], icon: 'getUp', desc: 'Levanta o jogador rapidamente após um carrinho para voltar à disputa.' },
        { name: 'Engajar Oponente Protegendo Bola', buttons: ['lt', 'ls'], icon: 'jostle', desc: 'Pressiona diretamente um adversário que está blindando a posse de bola.' },
        { name: 'Cancelar Vantagem de Falta', buttons: ['lt', 'rt'], icon: 'foul', desc: 'Interrompe a vantagem concedida após uma falta, voltando o jogo para a marcação.' }
    ],
    goleiro: [
        { name: 'Avançar Goleiro (Rush Out)', buttons: ['y'], icon: 'keeperRush', desc: 'Faz o goleiro sair da linha para reduzir o ângulo do atacante.' },
        { name: 'Goleiro Avançar para Conter', buttons: ['y', 'y'], icon: 'keeperRush', desc: 'Avanço do goleiro em modo de contenção, sem se comprometer totalmente.' },
        { name: 'Goleiro Avançar para o Centro', buttons: ['y', 'y'], icon: 'keeperRush', desc: 'Reposiciona o goleiro para o centro do gol durante lances de perigo.' },
        { name: 'Cancelar Avanço ao Centro', buttons: ['y'], icon: 'keeperRush', desc: 'Cancela o movimento de avanço do goleiro, retornando à posição original.' },
        { name: 'Ativar Controle Manual do Goleiro', buttons: ['b'], icon: 'keeperCatch', desc: 'Assume o controle direto do goleiro para posicionar defesas manualmente.' },
        { name: 'Mover Goleiro (Be a Goalkeeper)', buttons: ['ls'], icon: 'keeperCatch', desc: 'Movimenta o goleiro pela área durante o controle manual ativo.' },
        { name: 'Pegar a Bola (Grab Ball)', buttons: ['a'], icon: 'keeperCatch', desc: 'Faz o goleiro agarrar a bola em vez de apenas espalmar ou socar.' },
        { name: 'Socar a Bola (Punch)', buttons: ['x'], icon: 'keeperPunch', desc: 'O goleiro afasta a bola com os punhos em vez de tentar segurá-la.' },
        { name: 'Defesa por Reação (On Demand)', buttons: ['b'], icon: 'keeperDive', desc: 'Ativa uma defesa reativa manual no exato momento do chute adversário.' },
        { name: 'Blindar Área (Jockey Goleiro)', buttons: ['lt'], icon: 'shield', desc: 'Mantém o goleiro posicionado e atento sem se comprometer no lance.' },
        { name: 'Avançar do Gol (Rush)', buttons: ['rt'], icon: 'keeperRush', desc: 'Corre para fora da área em jogadas de escanteio ou bola alçada.' },
        { name: 'Sprint do Goleiro', buttons: ['rt'], icon: 'sprint', desc: 'Aumenta a velocidade de deslocamento do goleiro durante o controle manual.' },
        { name: 'Alternar para Controles de Linha', buttons: ['lb'], icon: 'switchPlayer', desc: 'Sai do controle do goleiro e volta a controlar os jogadores de linha.' },
        { name: 'Girar Câmera (Camera Pan)', buttons: ['rs'], icon: 'camera', desc: 'Gira a câmera durante o controle do goleiro para melhor visão do lance.' },
        { name: 'Tiro de Meta - Curto', buttons: ['a'], icon: 'keeperKick', desc: 'Reposição curta de bola com os pés após o tiro de meta.' },
        { name: 'Tiro de Meta - Longo', buttons: ['x'], icon: 'keeperKick', desc: 'Reposição longa de bola, lançando para o campo de ataque.' },
        { name: 'Reposição com a Mão', buttons: ['a'], icon: 'keeperThrow', desc: 'O goleiro lança a bola com a mão para um companheiro próximo.' }
    ],
    movimentacao: [
        { name: 'Mover Jogador', buttons: ['ls'], icon: 'sprint', desc: 'Movimento básico do jogador em qualquer direção do campo.' },
        { name: 'Sprint', buttons: ['rt'], icon: 'sprint', desc: 'Aumenta a velocidade de corrida, mas reduz um pouco o controle da bola.' },
        { name: 'Proteger a Bola (Shield)', buttons: ['lt'], icon: 'shield', desc: 'Posiciona o corpo entre a bola e o adversário para protegê-la.' },
        { name: 'Blindar / Jockey', buttons: ['lt'], icon: 'shield', desc: 'Movimento defensivo de acompanhamento mantendo distância segura.' },
        { name: 'Toque Controlado (First Touch)', buttons: ['rt', 'rs'], icon: 'firstTouch', desc: 'Controla a direção do primeiro toque ao receber um passe em corrida.' },
        { name: 'Toque com Efeito (Knock-On)', buttons: ['rt', 'rs'], icon: 'firstTouch', desc: 'Empurra a bola à frente para ganhar espaço logo após recebê-la.' },
        { name: 'Toque Controlado Avançado', buttons: ['rb', 'rs'], icon: 'firstTouch', desc: 'Toque mais discreto para manter a bola sob controle em espaço apertado.' },
        { name: 'Toque de Esforço', buttons: ['rb', 'rs'], icon: 'firstTouch', desc: 'Toque mais forte para acelerar a saída em jogadas de contra-ataque.' },
        { name: 'Parar e Encarar o Gol', buttons: ['ls', 'lb'], icon: 'stop', desc: 'Encerra a corrida e vira o corpo em direção ao gol adversário.' },
        { name: 'Drible Lateral (Strafe Dribble)', buttons: ['lb', 'ls'], icon: 'ballRoll', desc: 'Movimento lateral que mantém a bola protegida do lado do defensor.' },
        { name: 'Sprint Controlado', buttons: ['rb'], icon: 'sprint', desc: 'Corrida com maior domínio da bola, ideal em espaços apertados.' },
        { name: 'Parar a Bola', buttons: ['ls', 'rt'], icon: 'stop', desc: 'Trava a bola embaixo do pé para mudar o ritmo do ataque.' },
        { name: 'Disputa Física com Bola no Ar (Jostle)', buttons: ['lt'], icon: 'jostle', desc: 'Disputa de posição corporal enquanto a bola está no ar.' },
        { name: 'Jogadas de Habilidade', buttons: ['rs'], icon: 'skillMove', desc: 'Acesso rápido às fintas e dribles usando o analógico direito.' }
    ],
    cruzamentos: [
        { name: 'Cruzamento Padrão', buttons: ['x'], icon: 'cross', desc: 'Cruzamento básico para a área, direcionado pela posição do analógico.' },
        { name: 'Cruzamento Alto', buttons: ['lb', 'x'], icon: 'cross', desc: 'Cruzamento mais alto e arqueado, favorece jogadores fortes no cabeceio.' },
        { name: 'Cruzamento Forte (Driven)', buttons: ['lb', 'rb', 'x'], icon: 'cross', desc: 'Cruzamento rápido e rasteiro, difícil de cortar pela zaga adversária.' },
        { name: 'Cruzamento Duplo Toque', buttons: ['x', 'x'], icon: 'cross', desc: 'Cruzamento mais ágil ao apertar o botão duas vezes em sequência.' },
        { name: 'Cruzamento Rasteiro Forte', buttons: ['lb', 'rb', 'x', 'x'], icon: 'cross', desc: 'Combina velocidade e trajetória baixa para cruzamentos surpresa.' },
        { name: 'Cruzamento Categorizado (Flair)', buttons: ['lt', 'x'], icon: 'cross', desc: 'Cruzamento com efeito extra, útil para contornar defensores na linha de fundo.' },
        { name: 'Cruzamento de Precisão', buttons: ['rb', 'x'], icon: 'cross', desc: 'Cruzamento com trajetória mais controlada, direcionado com maior exatidão.' },
        { name: 'Cancelar Cruzamento (Fake)', buttons: ['x', 'a'], icon: 'fake', desc: 'Inicia o gesto de cruzamento e cancela, confundindo a defesa adversária.' },
        { name: 'Chamar Companheiro na Área', buttons: ['rb'], icon: 'support', desc: 'Pede que um companheiro se movimente para a área antes do cruzamento.' },
        { name: 'Corrida Direcional para Cruzamento', buttons: ['lb', 'rs'], icon: 'support', desc: 'Direciona a corrida de um companheiro para o ponto ideal de cruzamento.' }
    ],
    faltas: [
        { name: 'Bater Falta', buttons: ['b'], icon: 'freekick', desc: 'Executa a cobrança de falta direta a gol com a barra de força.' },
        { name: 'Mirar a Falta', buttons: ['ls'], icon: 'freekick', desc: 'Ajusta a mira horizontal da cobrança antes de bater a falta.' },
        { name: 'Ajustar Retícula de Efeito', buttons: ['rs'], icon: 'freekick', desc: 'Controla a curva e o efeito da bola durante a cobrança de falta.' },
        { name: 'Passe Curto na Falta', buttons: ['a'], icon: 'passShort', desc: 'Em vez de finalizar, toca a bola curta para um companheiro na cobrança.' },
        { name: 'Cavadinha na Falta', buttons: ['x'], icon: 'chip', desc: 'Cobrança de falta por cima da barreira em direção à área.' },
        { name: 'Pular na Barreira', buttons: ['y'], icon: 'wall', desc: 'Faz um jogador da barreira pular no momento da cobrança adversária.' },
        { name: 'Bater o Escanteio (Lob)', buttons: ['x'], icon: 'corner', desc: 'Cobrança de escanteio alçada para a área, ideal para cabeceio.' },
        { name: 'Passe Curto no Escanteio', buttons: ['a'], icon: 'corner', desc: 'Toca curto para um companheiro próximo em vez de cruzar direto.' },
        { name: 'Mirar o Escanteio', buttons: ['ls'], icon: 'corner', desc: 'Ajusta a direção da cobrança de escanteio antes de bater.' },
        { name: 'Ajustar Tática do Escanteio', buttons: ['dpad'], icon: 'tactic', desc: 'Abre o menu de jogadas ensaiadas para escanteios cadastradas na tática.' },
        { name: 'Cobrar Pênalti - Colocado', buttons: ['rb', 'b'], icon: 'penalty', desc: 'Cobrança de pênalti com mais precisão, mirando o canto do gol.' },
        { name: 'Cobrar Pênalti - Cavadinha', buttons: ['lb', 'b'], icon: 'penalty', desc: 'Cobrança de pênalti por cobertura, arriscada mas eficaz se bem cronometrada.' },
        { name: 'Segundo Batedor - Cavadinha', buttons: ['x'], icon: 'chip', desc: 'Em jogadas ensaiadas, o segundo jogador toca de cavadinha para o batedor.' },
        { name: 'Refazer Cobrança (Kick Off)', buttons: ['lt', 'rt', 'view'], icon: 'rewind', desc: 'Reinicia a cobrança de bola parada, disponível apenas no modo Kick Off.' }
    ]
};